apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: orders-app-deployment
  name: orders-app-deployment
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/orders-app-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: orders-app-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: orders-app-deployment
    spec:
      containers:
        #Refers to Container Registry. Structure: hostName/repository-name/container-name
        - image: asia.gcr.io/order-management-system/orders-app
          imagePullPolicy: Always
          name: orders-app
          ports:
            - containerPort: 3200
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3200
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
          resources:
            requests:
              memory: "750Mi"
              cpu: "100m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: NODE_OPTIONS
                valueFrom:
                  configMapKeyRef:
                    name: orders-app-configmap   
                    key: node_options 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-app-configmap
data:
  
  node_options: "--max_old_space_size=10000"

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: orders-app-deployment
  name: orders-app-service
  selfLink: /api/v1/namespaces/default/services/orders-app-service
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: orders-app-port
      port: 80
      protocol: TCP
      targetPort: 3200
  selector:
    run: orders-app-deployment
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
